
services:

  nginx:
    container_name: nginx
    build:  ./requirements/nginx
    image: nginx:1.0
    ports:
      - "305:305"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    image: wordpress:1.0
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html

    env_file:
      - .env

    restart: always
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    image: mariadb:1.0 
    networks:
      - inception
    volumes:
      - mariadb_data:/var/lib/mysql
    
    env_file:
      - .env
    restart: always

networks:
  inception:

# need to do a bind month for these volumes 
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ylagzoul/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ylagzoul/data/wordpress


